/**
 * subtitle.ts - 字幕领域类型
 *
 * 字幕来源：
 * - 手动字幕 (subtitles)：创作者上传的字幕
 * - 自动生成字幕 (automatic_captions)：YouTube 语音识别生成
 *
 * yt-dlp 获取字幕内容的命令：
 * - 写入文件:  yt-dlp --write-subs --skip-download --sub-format srt <url>
 * - 输出到 stdout: yt-dlp --write-subs --skip-download --sub-format srt -o - <url>
 *
 * 预览模式：只取前 N 条，不写文件，直接解析 stdout 返回
 */

/** 单条字幕 */
export interface SubtitleCue {
  /** 序号（从 1 开始） */
  index: number;
  /** 开始时间（秒） */
  start: number;
  /** 结束时间（秒） */
  end: number;
  /** 开始时间戳 SRT 格式（如 "00:00:01,500"） */
  startTimestamp: string;
  /** 字幕文本 */
  text: string;
}

/** 字幕预览结果 */
export interface SubtitlePreview {
  /** 视频标题 */
  videoTitle: string;
  /** 字幕语言代码 */
  language: string;
  /** 字幕展示名 */
  languageName: string;
  /** 是否为自动生成字幕 */
  isAutoGenerated: boolean;
  /** 字幕条目（已截断到 maxCues） */
  cues: SubtitleCue[];
  /** 总条目数（可能远大于 cues.length） */
  totalCount: number;
  /** 是否已截断 */
  truncated: boolean;
}

/** 字幕下载请求 */
export interface DownloadSubtitleRequest {
  /** 视频 URL 或 ID */
  url: string;
  /** 语言代码（如 zh-Hans / en） */
  language: string;
  /** 是否使用自动生成字幕 */
  autoGenerated: boolean;
  /** 输出文件路径（不传则返回内容） */
  outputPath?: string;
}

/** 字幕下载结果 */
export interface DownloadSubtitleResult {
  /** 输出文件路径（outputPath 传入时） */
  outputPath?: string;
  /** 字幕内容（outputPath 未传入时） */
  content?: string;
  /** 总条目数 */
  cueCount: number;
}
