/**
 * video.ts — 领域模型（与 docs/youtube-downloader-design.md 3.5 节对齐）
 *
 * 这些是 yt-dlp 原始 JSON 经过"清洗"后的稳定结构。
 * 原则：宁缺毋滥 —— 只保留 UI 和下游模块真正需要的字段，
 * yt-dlp 原始字段发生变化时，只需修改 yt-dlp.service.ts 中的映射函数。
 */

/** 查询输入的类型（由 url-classifier 判定） */
export type QueryKind = 'video' | 'playlist' | 'channel' | 'search';

/** 本次元数据解析实际采用的身份。 */
export type AuthenticationMode = 'anonymous' | 'cookie';

/** YouTube request profile used to expose the returned format IDs. */
export type YoutubeAccessMode = 'pot' | 'direct';

/** 缩略图 */
export interface Thumbnail {
  url: string;
  width?: number;
  height?: number;
}

/** 可下载格式（视频流/音频流的组合描述） */
export interface VideoFormat {
  /** yt-dlp format_id，下载时通过 -f 指定 */
  formatId: string;
  /** 容器：mp4 / webm / m4a ... */
  container: string;
  /** 画质标签，如 "1080p" / "720p60" / "audio only" */
  qualityLabel: string;
  /** 分辨率（仅视频），如 "1920x1080" */
  resolution?: string;
  /** 预估文件大小（字节），可能为 undefined（yt-dlp 不总是提供） */
  filesize?: number;
  hasVideo: boolean;
  hasAudio: boolean;
  /** 视频编码，如 h264 / vp9 / av01；纯音频时为音频编码 */
  codec?: string;
}

/** 字幕轨道信息 */
export interface SubtitleInfo {
  /** 语言代码，如 zh-Hans / en */
  language: string;
  /** 展示名，如 "中文（简体）"（yt-dlp 未提供时回退为 language） */
  name: string;
  /** 是否为 YouTube 自动生成字幕（语音识别） */
  isAutoGenerated: boolean;
}

/** 单个视频的标准化信息 */
export interface VideoInfo {
  id: string;
  title: string;
  /** 匿名优先；只有匿名解析失败后才标记为 Cookie 兜底。 */
  authentication?: AuthenticationMode;
  /** 下载必须复用该策略，否则同一格式 ID 可能消失。 */
  accessMode?: YoutubeAccessMode;
  /** 时长（秒），直播/未知时为 undefined */
  duration?: number;
  thumbnails: Thumbnail[];
  /** 上传日期 ISO 格式（yyyy-MM-dd），可能缺失 */
  uploadDate?: string;
  channelTitle?: string;
  /** 所属播放列表标题（从播放列表解析时填充） */
  playlistTitle?: string;
  /** 在播放列表中的序号（从 1 开始） */
  playlistIndex?: number;
  /** 可用格式列表；flat-playlist 模式下为空数组（详情按需再取） */
  formats: VideoFormat[];
  /** 可用字幕列表；同上 */
  subtitles: SubtitleInfo[];
}

/** 解析结果 —— 单视频 */
export interface VideoResolveResult {
  kind: 'video';
  title: string;
  videos: [VideoInfo];
}

/** 解析结果 —— 播放列表/频道（含多条视频） */
export interface PlaylistResolveResult {
  kind: 'playlist' | 'channel';
  title: string;
  channelTitle?: string;
  videoCount: number;
  videos: VideoInfo[];
}

/** /api/resolve 的联合返回类型 */
export type ResolveResult = VideoResolveResult | PlaylistResolveResult;
