/**
 * api.ts - 后端 API 类型定义与调用封装
 *
 * 与后端 server/types/ 下的类型手动对齐。
 * 统一处理 ApiResponse<T> 契约：成功取 data，失败抛出带 code 的 Error。
 */

// ==========================================
// 后端响应契约
// ==========================================

interface ApiSuccess<T> {
  success: true;
  data: T;
}

interface ApiFailure {
  success: false;
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}

type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

// ==========================================
// 领域类型（与后端对齐）
// ==========================================

export interface VideoInfo {
  id: string;
  title: string;
  duration?: number;
  thumbnails: { url: string; width?: number; height?: number }[];
  uploadDate?: string;
  channelTitle?: string;
  playlistTitle?: string;
  playlistIndex?: number;
  formats: VideoFormat[];
  subtitles: SubtitleInfo[];
}

export interface VideoFormat {
  formatId: string;
  container: string;
  qualityLabel: string;
  resolution?: string;
  filesize?: number;
  hasVideo: boolean;
  hasAudio: boolean;
  codec?: string;
}

export interface SubtitleInfo {
  language: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface SubtitleCue {
  index: number;
  start: number;
  end: number;
  startTimestamp: string;
  text: string;
}

export interface SubtitlePreview {
  videoTitle: string;
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
  totalCount: number;
  truncated: boolean;
}

export interface DownloadSubtitleResult {
  outputPath?: string;
  content?: string;
  cueCount: number;
}

export type ResolveResult =
  | { kind: 'video'; title: string; videos: [VideoInfo] }
  | {
      kind: 'playlist' | 'channel';
      title: string;
      channelTitle?: string;
      videoCount: number;
      videos: VideoInfo[];
    };

export type DownloadStatus =
  | 'queued'
  | 'downloading'
  | 'retrying'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'paused';

export interface DownloadTask {
  id: string;
  videoId: string;
  title: string;
  playlistTitle?: string;
  playlistIndex?: number;
  formatId: string;
  container: string;
  outputPath: string;
  subtitleLangs: string[];
  subtitleMode: 'embed' | 'separate' | 'none';
  autoSubtitle: boolean;
  status: DownloadStatus;
  progress: number;
  speed: string;
  eta: string;
  downloadedBytes: number;
  totalBytes: number;
  estimatedBytes: number;
  retryCount: number;
  maxRetries: number;
  nextRetryAt?: string;
  error?: string;
  errorCode?: string;
  createdAt: string;
  completedAt?: string;
}

export interface QueueStatus {
  tasks: DownloadTask[];
  active: number;
  waiting: number;
  completed: number;
  failed: number;
}

export interface HistoryPage {
  tasks: DownloadTask[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface CookieStatus {
  configured: boolean;
  source: 'file' | 'browser' | 'none';
  browser?: string;
  fileName?: string;
  updatedAt?: string;
}

export interface RuntimeToolStatus {
  available: boolean;
  version?: string;
  message?: string;
}

export interface HealthStatus {
  status: 'ok';
  uptime: number;
  runtime: {
    ytDlp: RuntimeToolStatus;
    ffmpeg: RuntimeToolStatus;
  };
}

export interface YtDlpUpdateStatus {
  currentVersion?: string;
  installedVersion?: string;
  source: 'updated' | 'bundled' | 'custom' | 'path';
  updateSupported: boolean;
  channel: 'nightly';
  restartRequired: boolean;
  message?: string;
}

export interface AppSettingsStatus {
  downloadPath: string;
  maxConcurrent: number;
  maxRetries: number;
  namingTemplate: string;
  proxyUrl: string;
  gentleMode: boolean;
  gentleRateLimitMbps: number;
  gentleCooldownSeconds: number;
  gentleBatchLimit: number;
  persistent: boolean;
}

export type UpdateAppSettingsInput = Partial<
  Pick<AppSettingsStatus, 'downloadPath' | 'maxConcurrent' | 'maxRetries' | 'namingTemplate' | 'proxyUrl' | 'gentleMode' | 'gentleRateLimitMbps' | 'gentleCooldownSeconds' | 'gentleBatchLimit'>
>;

export interface ConnectivityStatus {
  ok: boolean;
  code: string;
  message: string;
  recommendation?: string;
  testedAt: string;
  elapsedMs: number;
  proxyConfigured: boolean;
  cookieConfigured: boolean;
  videoTitle?: string;
}

export interface CreateDownloadTaskInput {
  videoId: string;
  title: string;
  playlistTitle?: string;
  playlistIndex?: number;
  formatId?: string;
  container?: string;
  subtitleLangs?: string[];
  subtitleMode?: 'embed' | 'separate' | 'none';
  autoSubtitle?: boolean;
  estimatedBytes?: number;
}

export type DownloadConflictPolicy = 'reject' | 'rename';

export interface DownloadConflict {
  inputIndex: number;
  title: string;
  outputPath: string;
  reason: 'existing_task' | 'file_exists' | 'batch_duplicate';
  existingTaskId?: string;
}

export interface CreateDownloadResponse {
  taskIds: string[];
  conflicts: DownloadConflict[];
  renamed: { inputIndex: number; title: string; outputPath: string }[];
}

// ==========================================
// API 错误
// ==========================================

export class ApiError extends Error {
  readonly code: string;
  readonly details?: unknown;
  /** HTTP 状态码（网络错误时为 0） */
  readonly statusCode: number;
  constructor(code: string, message: string, details?: unknown, statusCode = 0) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.details = details;
    this.statusCode = statusCode;
  }

  /** 是否为网络错误（离线/无法连接服务器） */
  isNetworkError(): boolean {
    return this.code === 'NETWORK_ERROR' || this.statusCode === 0;
  }

  /** 是否为可重试错误（网络错误或 5xx） */
  isRetryable(): boolean {
    return this.isNetworkError() || (this.statusCode >= 500 && this.statusCode < 600);
  }
}

// ==========================================
// 请求封装（带网络异常重试）
// ==========================================

const BASE = '/api';

/** 可重试的请求最大重试次数 */
const MAX_RETRIES = 2;

/** 重试延迟（毫秒） */
const RETRY_DELAY_MS = 1000;

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let lastError: ApiError | null = null;
  // Only retry idempotent reads. Retrying POST/DELETE after a lost response can
  // duplicate downloads, updates, or destructive actions.
  const method = (init?.method ?? 'GET').toUpperCase();
  const retryLimit = method === 'GET' || method === 'HEAD' ? MAX_RETRIES : 0;

  for (let attempt = 0; attempt <= retryLimit; attempt++) {
    try {
      // 检查网络连接
      if (!navigator.onLine && attempt === 0) {
        throw new ApiError('NETWORK_ERROR', '网络不可用，请检查网络连接');
      }

      const res = await fetch(`${BASE}${path}`, {
        headers: { 'Content-Type': 'application/json' },
        ...init,
      });

      let body: ApiResponse<T>;
      try {
        body = (await res.json()) as ApiResponse<T>;
      } catch {
        throw new ApiError('UNKNOWN', `服务器返回了非 JSON 响应 (HTTP ${res.status})`, undefined, res.status);
      }

      if (body.success) {
        return body.data;
      }

      // 业务错误，不重试
      throw new ApiError(body.error.code, body.error.message, body.error.details, res.status);
    } catch (err) {
      // ApiError 但不可重试，直接抛出
      if (err instanceof ApiError && !err.isRetryable()) {
        throw err;
      }

      // 网络错误或可重试错误
      const isNetworkErr = err instanceof TypeError || (err instanceof ApiError && err.isNetworkError());
      lastError = isNetworkErr
        ? new ApiError('NETWORK_ERROR', '无法连接到服务器，请确认后端服务已启动')
        : err instanceof ApiError ? err : new ApiError('UNKNOWN', String(err));

      // 最后一次尝试不再等待
      if (attempt < retryLimit && lastError.isRetryable()) {
        await sleep(RETRY_DELAY_MS * (attempt + 1));
        continue;
      }
    }
  }

  throw lastError ?? new ApiError('UNKNOWN', '请求失败');
}

// ==========================================
// API 方法
// ==========================================

export const api = {
  getHealth: () => request<HealthStatus>('/health'),
  getYtDlpUpdateStatus: () => request<YtDlpUpdateStatus>('/runtime/yt-dlp'),
  updateYtDlp: () => request<YtDlpUpdateStatus>('/runtime/yt-dlp/update', { method: 'POST' }),
  testConnectivity: () => request<ConnectivityStatus>('/runtime/connectivity', { method: 'POST' }),
  getSettings: () => request<AppSettingsStatus>('/settings'),
  updateSettings: (settings: UpdateAppSettingsInput) =>
    request<AppSettingsStatus>('/settings', {
      method: 'PUT',
      body: JSON.stringify(settings),
    }),

  // 解析
  resolve: (url: string) =>
    request<ResolveResult>(`/resolve?url=${encodeURIComponent(url)}`),

  // 下载
  createDownload: (tasks: CreateDownloadTaskInput[], conflictPolicy: DownloadConflictPolicy = 'reject') =>
    request<CreateDownloadResponse>('/download', {
      method: 'POST',
      body: JSON.stringify({ tasks, conflictPolicy }),
    }),

  getFormats: (url: string) =>
    request<{ videoId: string; title: string; formats: VideoFormat[]; subtitles: SubtitleInfo[] }>(
      `/download/formats?url=${encodeURIComponent(url)}`,
    ),

  // 队列
  getQueue: () => request<QueueStatus>('/queue'),

  pauseTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}/pause`, { method: 'POST' }),

  resumeTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}/resume`, { method: 'POST' }),

  cancelTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}/cancel`, { method: 'POST' }),

  removeTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}`, { method: 'DELETE' }),

  // 历史
  getHistory: (page = 1, pageSize = 50) =>
    request<HistoryPage>(`/history?page=${page}&pageSize=${pageSize}`),

  deleteHistory: (id: string) =>
    request<{ deleted: boolean; id: string }>(`/history/${id}`, {
      method: 'DELETE',
    }),

  clearHistory: () =>
    request<{ deleted: number }>('/history', { method: 'DELETE' }),

  retryHistory: (id: string) =>
    request<QueueStatus>(`/history/${id}/retry`, { method: 'POST' }),

  // Cookie
  getCookieStatus: () => request<CookieStatus>('/auth/cookie'),

  setCookieFile: (content: string) =>
    request<CookieStatus>('/auth/cookie/file', {
      method: 'POST',
      body: JSON.stringify({ content }),
    }),

  setCookieBrowser: (browser: string) =>
    request<CookieStatus>('/auth/cookie/browser', {
      method: 'POST',
      body: JSON.stringify({ browser }),
    }),

  clearCookie: () =>
    request<CookieStatus>('/auth/cookie', { method: 'DELETE' }),

  // 字幕
  previewSubtitle: (url: string, language: string, autoGenerated: boolean, maxCues = 5) =>
    request<SubtitlePreview>(
      `/subtitle/preview?url=${encodeURIComponent(url)}&language=${encodeURIComponent(language)}&autoGenerated=${autoGenerated}&maxCues=${maxCues}`,
    ),

  downloadSubtitle: (url: string, language: string, autoGenerated: boolean) =>
    request<DownloadSubtitleResult>('/subtitle/download', {
      method: 'POST',
      body: JSON.stringify({ url, language, autoGenerated }),
    }),
};
