/**
 * api.ts - 后端 API 类型定义与调用封装
 *
 * 与后端 server/types/ 下的类型手动对齐。
 * 统一处理 ApiResponse<T> 契约：成功取 data，失败抛出带 code 的 Error。
 */

// ==========================================
// 后端响应契约
// ==========================================

interface ApiSuccess<T> {
  success: true;
  data: T;
}

interface ApiFailure {
  success: false;
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}

type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

// ==========================================
// 领域类型（与后端对齐）
// ==========================================

export interface VideoInfo {
  id: string;
  title: string;
  duration?: number;
  thumbnails: { url: string; width?: number; height?: number }[];
  uploadDate?: string;
  channelTitle?: string;
  playlistTitle?: string;
  playlistIndex?: number;
  formats: VideoFormat[];
  subtitles: SubtitleInfo[];
}

export interface VideoFormat {
  formatId: string;
  container: string;
  qualityLabel: string;
  resolution?: string;
  filesize?: number;
  hasVideo: boolean;
  hasAudio: boolean;
  codec?: string;
}

export interface SubtitleInfo {
  language: string;
  name: string;
  isAutoGenerated: boolean;
}

export type ResolveResult =
  | { kind: 'video'; title: string; videos: [VideoInfo] }
  | {
      kind: 'playlist' | 'channel';
      title: string;
      channelTitle?: string;
      videoCount: number;
      videos: VideoInfo[];
    };

export type DownloadStatus =
  | 'queued'
  | 'downloading'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'paused';

export interface DownloadTask {
  id: string;
  videoId: string;
  title: string;
  playlistTitle?: string;
  playlistIndex?: number;
  formatId: string;
  container: string;
  outputPath: string;
  subtitleLangs: string[];
  subtitleMode: 'embed' | 'separate' | 'none';
  autoSubtitle: boolean;
  status: DownloadStatus;
  progress: number;
  speed: string;
  eta: string;
  downloadedBytes: number;
  totalBytes: number;
  error?: string;
  createdAt: string;
  completedAt?: string;
}

export interface QueueStatus {
  tasks: DownloadTask[];
  active: number;
  waiting: number;
  completed: number;
  failed: number;
}

export interface CookieStatus {
  configured: boolean;
  source: 'file' | 'browser' | 'none';
  browser?: string;
  fileName?: string;
  updatedAt?: string;
}

export interface CreateDownloadTaskInput {
  videoId: string;
  title: string;
  playlistTitle?: string;
  playlistIndex?: number;
  formatId?: string;
  container?: string;
  subtitleLangs?: string[];
  subtitleMode?: 'embed' | 'separate' | 'none';
  autoSubtitle?: boolean;
}

// ==========================================
// API 错误
// ==========================================

export class ApiError extends Error {
  readonly code: string;
  readonly details?: unknown;
  constructor(code: string, message: string, details?: unknown) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.details = details;
  }
}

// ==========================================
// 请求封装
// ==========================================

const BASE = '/api';

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...init,
  });

  let body: ApiResponse<T>;
  try {
    body = (await res.json()) as ApiResponse<T>;
  } catch {
    throw new ApiError('UNKNOWN', `服务器返回了非 JSON 响应 (HTTP ${res.status})`);
  }

  if (body.success) {
    return body.data;
  }

  throw new ApiError(body.error.code, body.error.message, body.error.details);
}

// ==========================================
// API 方法
// ==========================================

export const api = {
  // 解析
  resolve: (url: string) =>
    request<ResolveResult>(`/resolve?url=${encodeURIComponent(url)}`),

  // 下载
  createDownload: (tasks: CreateDownloadTaskInput[]) =>
    request<{ taskIds: string[] }>('/download', {
      method: 'POST',
      body: JSON.stringify({ tasks }),
    }),

  getFormats: (url: string) =>
    request<{ videoId: string; title: string; formats: VideoFormat[]; subtitles: SubtitleInfo[] }>(
      `/download/formats?url=${encodeURIComponent(url)}`,
    ),

  // 队列
  getQueue: () => request<QueueStatus>('/queue'),

  pauseTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}/pause`, { method: 'POST' }),

  resumeTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}/resume`, { method: 'POST' }),

  cancelTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}/cancel`, { method: 'POST' }),

  removeTask: (id: string) =>
    request<QueueStatus>(`/queue/${id}`, { method: 'DELETE' }),

  // Cookie
  getCookieStatus: () => request<CookieStatus>('/auth/cookie'),

  setCookieFile: (content: string) =>
    request<CookieStatus>('/auth/cookie/file', {
      method: 'POST',
      body: JSON.stringify({ content }),
    }),

  setCookieBrowser: (browser: string) =>
    request<CookieStatus>('/auth/cookie/browser', {
      method: 'POST',
      body: JSON.stringify({ browser }),
    }),

  clearCookie: () =>
    request<CookieStatus>('/auth/cookie', { method: 'DELETE' }),

  // 字幕
  previewSubtitle: (url: string, language: string, autoGenerated: boolean, maxCues = 5) =>
    request<{
      videoTitle: string;
      language: string;
      languageName: string;
      isAutoGenerated: boolean;
      cues: { index: number; start: number; end: number; startTimestamp: string; text: string }[];
      totalCount: number;
      truncated: boolean;
    }>(
      `/subtitle/preview?url=${encodeURIComponent(url)}&language=${encodeURIComponent(language)}&autoGenerated=${autoGenerated}&maxCues=${maxCues}`,
    ),
};
