import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import type { YtDlpService } from '../server/core/yt-dlp.service.ts';
import { SubtitleService } from '../server/services/subtitle.service.ts';
import { AppError } from '../server/types/errors.ts';

test('parses multiline SRT cues with comma and dot millisecond separators', () => {
  const service = new SubtitleService({} as YtDlpService, {
    binary: 'yt-dlp',
    outputRoot: 'C:\\Downloads',
  });
  const cues = service.parseSrt([
    '1',
    '00:00:01,500 --> 00:00:04,200',
    '第一行',
    '第二行',
    '',
    '2',
    '00:01:02.250 --> 00:01:03.500',
    'Next cue',
  ].join('\n'));

  assert.equal(cues.length, 2);
  assert.deepEqual(cues[0], {
    index: 1,
    start: 1.5,
    end: 4.2,
    startTimestamp: '00:00:01,500',
    text: '第一行\n第二行',
  });
  assert.equal(cues[1]?.start, 62.25);
});

test('downloads subtitles through a temporary SRT file and cleans it afterwards', async () => {
  let generatedTempDir = '';
  let observedArgs: string[] = [];
  const ytDlpService = {
    resolve: async () => ({
      kind: 'video' as const,
      title: 'Subtitle test',
      videos: [{
        id: 'YE7VzlLtp-4',
        title: 'Subtitle test',
        thumbnails: [],
        formats: [],
        subtitles: [{ language: 'en', name: 'English', isAutoGenerated: false }],
      }] as const,
    }),
  } as unknown as YtDlpService;
  const service = new SubtitleService(ytDlpService, {
    binary: 'fake-yt-dlp',
    ffmpegBinary: 'C:\\Tools\\ffmpeg.exe',
    outputRoot: 'C:\\Downloads',
    getProxyUrl: () => 'socks5://127.0.0.1:1080',
    runProcess: async (_command, args) => {
      observedArgs = args;
      const outputIndex = args.indexOf('-o');
      assert.ok(outputIndex >= 0);
      const outputTemplate = args[outputIndex + 1];
      assert.ok(outputTemplate);
      generatedTempDir = path.dirname(outputTemplate);
      fs.writeFileSync(
        path.join(generatedTempDir, 'subtitle.en.srt'),
        '1\n00:00:00,000 --> 00:00:01,000\nHello\n',
        'utf8',
      );
      return { stdout: '', stderr: '', exitCode: 0, durationMs: 1 };
    },
  });

  const result = await service.download(
    'https://www.youtube.com/watch?v=YE7VzlLtp-4',
    'en',
    false,
  );
  assert.match(result.content ?? '', /Hello/);
  assert.equal(result.cueCount, 1);
  assert.ok(observedArgs.includes('--ffmpeg-location'));
  assert.deepEqual(observedArgs.slice(-3), [
    '--proxy',
    'socks5://127.0.0.1:1080',
    'https://www.youtube.com/watch?v=YE7VzlLtp-4',
  ]);
  assert.equal(fs.existsSync(generatedTempDir), false);
});

test('reports browser Cookie extraction failures while fetching subtitles', async () => {
  const ytDlpService = {
    resolve: async () => ({
      kind: 'video' as const,
      title: 'Subtitle Cookie test',
      videos: [{
        id: 'YE7VzlLtp-4',
        title: 'Subtitle Cookie test',
        thumbnails: [],
        formats: [],
        subtitles: [{ language: 'en', name: 'English', isAutoGenerated: false }],
      }],
    }),
  } as unknown as YtDlpService;
  const service = new SubtitleService(ytDlpService, {
    binary: 'fake-yt-dlp',
    outputRoot: 'C:\\Downloads',
    runProcess: async () => ({
      stdout: '',
      stderr: 'ERROR: Could not copy Chrome cookie database. See issue 7271',
      exitCode: 1,
      durationMs: 1,
    }),
  });

  await assert.rejects(
    service.download('https://www.youtube.com/watch?v=YE7VzlLtp-4', 'en', false),
    (error: unknown) => error instanceof AppError && error.code === 'COOKIE_ERROR',
  );
});

test('keeps unavailable subtitle tracks as a specific not-found error', async () => {
  const ytDlpService = {
    resolve: async () => ({
      kind: 'video' as const,
      title: 'Missing subtitle test',
      videos: [{
        id: 'YE7VzlLtp-4',
        title: 'Missing subtitle test',
        thumbnails: [],
        formats: [],
        subtitles: [{ language: 'zh-Hans', name: '简体中文', isAutoGenerated: false }],
      }],
    }),
  } as unknown as YtDlpService;
  const service = new SubtitleService(ytDlpService, {
    binary: 'fake-yt-dlp',
    outputRoot: 'C:\\Downloads',
    runProcess: async () => ({
      stdout: '',
      stderr: 'ERROR: requested subtitles are not available',
      exitCode: 1,
      durationMs: 1,
    }),
  });

  await assert.rejects(
    service.download('https://www.youtube.com/watch?v=YE7VzlLtp-4', 'zh-Hans', false),
    (error: unknown) => error instanceof AppError && error.code === 'NOT_FOUND',
  );
});
