/**
 * routes/subtitle.ts - 字幕相关路由
 *
 * GET  /api/subtitle/preview   预览字幕（前 N 条）
 * POST /api/subtitle/download  下载完整字幕到文件或返回内容
 *
 * 查询参数/请求体设计：
 * - preview: url + language + autoGenerated + maxCues（默认 5）
 * - download: url + language + autoGenerated + outputPath（可选）
 */

import { Router } from 'express';
import type { SubtitleService } from '../services/subtitle.service.ts';
import { asyncHandler } from '../core/utils.ts';
import { AppError } from '../types/errors.ts';
import { ok } from '../types/result.ts';

export function createSubtitleRouter(subtitleService: SubtitleService): Router {
  const router = Router();

  // -- 预览字幕（前 N 条）--
  router.get(
    '/preview',
    asyncHandler(async (req, res) => {
      const url = req.query.url;
      const language = req.query.language;
      const autoGenerated = req.query.autoGenerated === 'true';
      const maxCues = req.query.maxCues
        ? parseInt(req.query.maxCues as string, 10)
        : 5;

      if (typeof url !== 'string' || url.trim().length === 0) {
        throw new AppError('MISSING_PARAM', '缺少必需参数: url');
      }
      if (typeof language !== 'string' || language.trim().length === 0) {
        throw new AppError('MISSING_PARAM', '缺少必需参数: language（如 zh-Hans / en）');
      }

      const preview = await subtitleService.preview(
        url,
        language,
        autoGenerated,
        maxCues,
      );
      res.json(ok(preview));
    }),
  );

  // -- 下载完整字幕 --
  router.post(
    '/download',
    asyncHandler(async (req, res) => {
      const body = req.body as {
        url?: string;
        language?: string;
        autoGenerated?: boolean;
        outputPath?: string;
      };

      if (!body?.url || typeof body.url !== 'string') {
        throw new AppError('MISSING_PARAM', '请求体需包含 url 字段');
      }
      if (!body?.language || typeof body.language !== 'string') {
        throw new AppError('MISSING_PARAM', '请求体需包含 language 字段');
      }

      const result = await subtitleService.download(
        body.url,
        body.language,
        body.autoGenerated ?? false,
        body.outputPath,
      );
      res.json(ok(result));
    }),
  );

  return router;
}
