/**
 * subtitle.service.ts - 字幕预览与下载服务
 *
 * 职责：
 * - 预览字幕：只取前 N 条，不写文件，直接解析 yt-dlp stdout
 * - 下载字幕：写入指定路径或返回完整内容
 *
 * yt-dlp 字幕获取命令模式：
 *   yt-dlp --skip-download --write-subs --sub-langs <lang> --sub-format srt -o - <url>
 *
 * 说明：
 * - --write-subs 获取手动字幕，--write-auto-subs 获取自动生成字幕
 * - -o - 将字幕输出到 stdout（而非写入文件），便于直接解析
 * - --sub-format srt 统一用 SRT 格式（yt-dlp 会自动转换 vtt）
 *
 * SRT 格式：
 *   1
 *   00:00:01,500 --> 00:00:04,200
 *   字幕文本第一行
 *   字幕文本第二行
 *
 *   2
 *   ...
 */

import { runProcess } from '../core/process.ts';
import { AppError } from '../types/errors.ts';
import path from 'node:path';
import fs from 'node:fs';
import type { CookieArg } from '../types/auth.ts';
import type { SubtitleCue, SubtitlePreview } from '../types/subtitle.ts';
import type { YtDlpService } from '../core/yt-dlp.service.ts';

export interface SubtitleServiceOptions {
  binary: string;
  /** 字幕输出只能落在该目录内。 */
  outputRoot: string;
  getCookieArg?: () => CookieArg | undefined;
}

export class SubtitleService {
  private readonly binary: string;
  private outputRoot: string;
  private readonly getCookieArg?: () => CookieArg | undefined;
  private readonly ytDlpService: YtDlpService;

  constructor(ytDlpService: YtDlpService, options: SubtitleServiceOptions) {
    this.ytDlpService = ytDlpService;
    this.binary = options.binary;
    this.outputRoot = path.resolve(options.outputRoot);
    this.getCookieArg = options.getCookieArg;
  }

  updateOutputRoot(outputRoot: string): void {
    this.outputRoot = path.resolve(outputRoot);
  }

  /**
   * 预览字幕：获取前 maxCues 条，不写文件。
   *
   * 流程：
   * 1. 先通过 YtDlpService.resolve 获取视频元数据（含字幕列表）
   * 2. 找到指定语言的字幕轨道
   * 3. 用 yt-dlp --write-subs -o - 获取字幕内容到 stdout
   * 4. 解析 SRT 取前 N 条
   *
   * @param url 视频 URL 或搜索关键词
   * @param language 字幕语言代码（如 zh-Hans / en）
   * @param autoGenerated 是否使用自动生成字幕
   * @param maxCues 预览条数上限，默认 5
   */
  async preview(
    url: string,
    language: string,
    autoGenerated: boolean,
    maxCues = 5,
  ): Promise<SubtitlePreview> {
    // 1. 解析视频，获取标题与字幕列表
    const result = await this.ytDlpService.resolve(url);
    const video = result.videos[0];
    if (!video) {
      throw new AppError('VIDEO_UNAVAILABLE', '未找到视频信息');
    }

    // 2. 查找匹配的字幕轨道
    const track = video.subtitles.find(
      (s) => s.language === language && s.isAutoGenerated === autoGenerated,
    );
    if (!track) {
      const available = video.subtitles
        .map((s) => `${s.language}${s.isAutoGenerated ? '(auto)' : ''}`)
        .join(', ');
      throw new AppError(
        'NOT_FOUND',
        `未找到语言 ${language}${autoGenerated ? '(自动生成)' : ''} 的字幕。可用: ${available || '无'}`,
      );
    }

    // 3. 获取字幕内容
    const srtContent = await this.fetchSubtitleSrt(
      video.id,
      language,
      autoGenerated,
    );

    // 4. 解析 SRT 并截断
    const allCues = this.parseSrt(srtContent);
    const cues = allCues.slice(0, maxCues);
    const truncated = allCues.length > maxCues;

    return {
      videoTitle: video.title,
      language: track.language,
      languageName: track.name,
      isAutoGenerated: track.isAutoGenerated,
      cues,
      totalCount: allCues.length,
      truncated,
    };
  }

  /**
   * 下载完整字幕到文件或返回内容。
   *
   * @returns 如果 outputPath 提供，写入文件并返回路径；否则返回内容字符串
   */
  async download(
    url: string,
    language: string,
    autoGenerated: boolean,
    outputPath?: string,
  ): Promise<{ outputPath?: string; content?: string; cueCount: number }> {
    // 先解析获取 videoId
    const result = await this.ytDlpService.resolve(url);
    const video = result.videos[0];
    if (!video) {
      throw new AppError('VIDEO_UNAVAILABLE', '未找到视频信息');
    }

    const content = await this.fetchSubtitleSrt(video.id, language, autoGenerated);
    const cueCount = this.parseSrt(content).length;

    if (outputPath?.trim()) {
      const resolvedPath = path.resolve(this.outputRoot, outputPath);
      const relativePath = path.relative(this.outputRoot, resolvedPath);
      const isOutsideRoot =
        relativePath === '..' ||
        relativePath.startsWith(`..${path.sep}`) ||
        path.isAbsolute(relativePath);
      if (isOutsideRoot) {
        throw new AppError(
          'PATH_NOT_ALLOWED',
          '字幕输出路径必须位于下载目录内',
          { outputRoot: this.outputRoot },
        );
      }

      const dir = path.dirname(resolvedPath);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(resolvedPath, content, 'utf8');
      return { outputPath: resolvedPath, cueCount };
    }

    return { content, cueCount };
  }

  // ------------------------------------------
  // 内部
  // ------------------------------------------

  /**
   * 调用 yt-dlp 获取字幕 SRT 内容（输出到 stdout）。
   *
   * 命令: yt-dlp --skip-download --write-{auto-}subs --sub-langs <lang> --sub-format srt -o - <url>
   *
   * -o -  让 yt-dlp 将字幕输出到 stdout 而非写文件。
   * 注意：yt-dlp 在 -o - 模式下，stdout 会包含字幕内容（可能混合少量信息行），
   * 我们只解析 SRT 块（从第一个数字序号行开始）。
   */
  private async fetchSubtitleSrt(
    videoId: string,
    language: string,
    autoGenerated: boolean,
  ): Promise<string> {
    const args: string[] = [
      '--skip-download',
      autoGenerated ? '--write-auto-subs' : '--write-subs',
      '--sub-langs', language,
      '--sub-format', 'srt',
      '--convert-subs', 'srt',
      '-o', '-',  // 输出到 stdout
      '--no-warnings',
      `https://www.youtube.com/watch?v=${videoId}`,
    ];

    // 注入 Cookie
    const cookieArg = this.getCookieArg?.();
    if (cookieArg) {
      args.splice(args.length - 1, 0, cookieArg.flag, cookieArg.value);
    }

    const result = await runProcess(this.binary, args, {
      timeoutMs: 30_000,
    });

    if (result.exitCode !== 0) {
      throw this.translateError(result.stderr);
    }

    // yt-dlp -o - 模式下，stdout 可能有前导信息行
    // 提取从第一个 SRT 序号行开始的内容
    return this.extractSrtBlock(result.stdout);
  }

  /**
   * 从 yt-dlp stdout 中提取 SRT 内容块。
   * SRT 块以数字序号行开始，前面可能有 [info] 等信息行。
   */
  private extractSrtBlock(stdout: string): string {
    const lines = stdout.split('\n');
    let startIndex = -1;

    for (let i = 0; i < lines.length; i++) {
      // SRT 序号行：纯数字
      const line = lines[i]!.trim();
      if (/^\d+$/.test(line) && i + 1 < lines.length) {
        // 下一行应该是时间戳行 --> 验证
        const nextLine = lines[i + 1] ?? '';
        if (nextLine.includes('-->')) {
          startIndex = i;
          break;
        }
      }
    }

    if (startIndex === -1) {
      // 没找到 SRT 块，可能 yt-dlp 输出了警告但没下载到字幕
      throw new AppError(
        'NOT_FOUND',
        '字幕获取失败：yt-dlp 未返回有效的 SRT 内容（可能该视频无此语言字幕）',
        { stdoutHead: stdout.slice(0, 200) },
      );
    }

    return lines.slice(startIndex).join('\n').trim();
  }

  /**
   * 解析 SRT 格式字幕。
   *
   * SRT 块格式：
   *   1
   *   00:00:01,500 --> 00:00:04,200
   *   字幕文本（可能多行）
   *
   *   2
   *   ...
   */
  parseSrt(srt: string): SubtitleCue[] {
    const cues: SubtitleCue[] = [];
    // SRT 块之间用空行分隔
    const blocks = srt.split(/\n\s*\n/);

    for (const block of blocks) {
      const lines = block.trim().split('\n');
      if (lines.length < 3) continue;

      // 第 1 行：序号
      const index = parseInt(lines[0]!.trim(), 10);
      if (!Number.isFinite(index)) continue;

      // 第 2 行：时间戳  00:00:01,500 --> 00:00:04,200
      const timeLine = lines[1] ?? '';
      const timeMatch = timeLine.match(
        /(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})/,
      );
      if (!timeMatch) continue;

      const startTimestamp = timeMatch[1]!;
      const endTimestamp = timeMatch[2]!;
      const start = this.timestampToSeconds(startTimestamp);
      const end = this.timestampToSeconds(endTimestamp);

      // 第 3 行起：字幕文本
      const text = lines.slice(2).join('\n').trim();

      cues.push({
        index,
        start,
        end,
        startTimestamp,
        text,
      });
    }

    return cues;
  }

  /** SRT 时间戳 "00:01:23,456" → 秒数 83.456 */
  private timestampToSeconds(ts: string): number {
    const match = ts.match(/(\d{2}):(\d{2}):(\d{2})[,.](\d{3})/);
    if (!match) return 0;
    const h = parseInt(match[1]!, 10);
    const m = parseInt(match[2]!, 10);
    const s = parseInt(match[3]!, 10);
    const ms = parseInt(match[4]!, 10);
    return h * 3600 + m * 60 + s + ms / 1000;
  }

  private translateError(stderr: string): AppError {
    const text = stderr.toLowerCase();
    if (text.includes('sign in to confirm') || text.includes('not a bot')) {
      return new AppError('RATE_LIMITED', 'YouTube 要求人机验证，请配置 Cookie', { stderr });
    }
    if (text.includes('video unavailable')) {
      return new AppError('VIDEO_UNAVAILABLE', '视频不可用', { stderr });
    }
    if (text.includes('subtitles') && text.includes('not available')) {
      return new AppError('NOT_FOUND', '该视频没有指定语言的字幕', { stderr });
    }
    return new AppError('UNKNOWN', '字幕获取失败', { stderr: stderr.slice(-300) });
  }
}
