'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');

const AUTH_COOKIE_NAMES = new Set([
  'SAPISID',
  '__Secure-1PAPISID',
  '__Secure-3PAPISID',
]);

function findChromeExecutable({ env = process.env, existsSync = fs.existsSync } = {}) {
  const candidates = [
    env.PROGRAMFILES && path.join(env.PROGRAMFILES, 'Google', 'Chrome', 'Application', 'chrome.exe'),
    env['PROGRAMFILES(X86)'] && path.join(env['PROGRAMFILES(X86)'], 'Google', 'Chrome', 'Application', 'chrome.exe'),
    env.LOCALAPPDATA && path.join(env.LOCALAPPDATA, 'Google', 'Chrome', 'Application', 'chrome.exe'),
  ].filter(Boolean);
  return candidates.find((candidate) => existsSync(candidate));
}

function buildChromeLoginArgs(profileDir) {
  return [
    `--user-data-dir=${profileDir}`,
    '--no-first-run',
    '--no-default-browser-check',
    '--new-window',
    'https://www.youtube.com/',
  ];
}

function buildChromeExportArgs(profileDir) {
  return [
    `--user-data-dir=${profileDir}`,
    '--remote-debugging-address=127.0.0.1',
    '--remote-debugging-port=0',
    '--headless=new',
    '--no-first-run',
    '--no-default-browser-check',
    'about:blank',
  ];
}

function parseDevToolsActivePort(content) {
  const [portLine, socketPath] = String(content).trim().split(/\r?\n/);
  const port = Number(portLine);
  if (!Number.isInteger(port) || port < 1 || port > 65535 || !socketPath?.startsWith('/')) {
    throw new Error('专用 Chrome 调试端口信息无效');
  }
  return `ws://127.0.0.1:${port}${socketPath}`;
}

function isYouTubeDomain(domain) {
  const normalized = String(domain ?? '').replace(/^\./, '').toLowerCase();
  return normalized === 'youtube.com' || normalized.endsWith('.youtube.com');
}

function serializeYouTubeCookies(cookies) {
  const filtered = Array.isArray(cookies)
    ? cookies.filter((cookie) => cookie && isYouTubeDomain(cookie.domain))
    : [];
  if (!filtered.some((cookie) => AUTH_COOKIE_NAMES.has(cookie.name))) {
    throw new Error('尚未检测到 YouTube 登录状态。请在专用 Chrome 窗口登录后再点“完成授权”。');
  }

  const lines = ['# Netscape HTTP Cookie File', '# Generated by YouTube Learning Downloader'];
  for (const cookie of filtered) {
    const domain = String(cookie.domain ?? '').trim();
    const cookiePath = String(cookie.path ?? '/').trim() || '/';
    const name = String(cookie.name ?? '').replace(/[\t\r\n]/g, '');
    const value = String(cookie.value ?? '').replace(/[\t\r\n]/g, '');
    if (!domain || !name) continue;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = Number.isFinite(cookie.expires) && cookie.expires > 0
      ? String(Math.floor(cookie.expires))
      : '0';
    const storedDomain = cookie.httpOnly ? `#HttpOnly_${domain}` : domain;
    lines.push([storedDomain, includeSubdomains, cookiePath, secure, expires, name, value].join('\t'));
  }
  return `${lines.join('\n')}\n`;
}

function sendCdpCommand(webSocketUrl, method, params = {}, options = {}) {
  const WebSocketImpl = options.WebSocketImpl ?? globalThis.WebSocket;
  const timeoutMs = options.timeoutMs ?? 10_000;
  if (typeof WebSocketImpl !== 'function') {
    return Promise.reject(new Error('当前运行环境不支持 Chrome 调试连接'));
  }
  return new Promise((resolve, reject) => {
    const socket = new WebSocketImpl(webSocketUrl);
    let settled = false;
    const timer = setTimeout(() => finish(new Error(`Chrome 调试命令超时：${method}`)), timeoutMs);

    const finish = (error, value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try { socket.close(); } catch { /* already closed */ }
      if (error) reject(error);
      else resolve(value);
    };

    socket.addEventListener('open', () => {
      socket.send(JSON.stringify({ id: 1, method, params }));
    });
    socket.addEventListener('message', (event) => {
      try {
        const message = JSON.parse(String(event.data));
        if (message.id !== 1) return;
        if (message.error) {
          finish(new Error(message.error.message ?? `Chrome 调试命令失败：${method}`));
          return;
        }
        finish(null, message.result);
      } catch (error) {
        finish(error);
      }
    });
    socket.addEventListener('close', () => {
      if (method === 'Browser.close') finish(null, {});
      else finish(new Error('专用 Chrome 调试连接已关闭'));
    });
    socket.addEventListener('error', () => finish(new Error('无法连接专用 Chrome 登录窗口')));
  });
}

function waitForDevToolsPort(activePortPath, child, options = {}) {
  const fsImpl = options.fsImpl ?? fs;
  const timeoutMs = options.timeoutMs ?? 15_000;
  const startedAt = Date.now();
  return new Promise((resolve, reject) => {
    const poll = () => {
      if (child.exitCode !== null) {
        reject(new Error('专用 Chrome 登录窗口启动后意外退出'));
        return;
      }
      try {
        resolve(parseDevToolsActivePort(fsImpl.readFileSync(activePortPath, 'utf8')));
        return;
      } catch (error) {
        if (Date.now() - startedAt >= timeoutMs) {
          reject(new Error(`专用 Chrome 启动超时：${error instanceof Error ? error.message : String(error)}`));
          return;
        }
      }
      setTimeout(poll, 100);
    };
    poll();
  });
}

function createYouTubeAuthController(options) {
  const profileDir = options.profileDir;
  const fsImpl = options.fsImpl ?? fs;
  const spawnProcess = options.spawnProcess ?? spawn;
  const cdpCommand = options.cdpCommand ?? sendCdpCommand;
  const waitForPort = options.waitForDevToolsPort ?? waitForDevToolsPort;
  let chromeExecutable = null;
  let loginChild = null;
  let exportChild = null;
  let webSocketUrl = null;

  function resolveChromeExecutable() {
    chromeExecutable ??= options.chromeExecutable ?? findChromeExecutable({
      env: options.env,
      existsSync: fsImpl.existsSync.bind(fsImpl),
    });
    if (!chromeExecutable) throw new Error('未找到 Google Chrome，请先安装 Chrome 后重试');
    return chromeExecutable;
  }

  async function start() {
    if (loginChild && loginChild.exitCode === null) return { started: true, reused: true };
    fsImpl.mkdirSync(profileDir, { recursive: true });
    loginChild = spawnProcess(resolveChromeExecutable(), buildChromeLoginArgs(profileDir), {
      stdio: 'ignore',
      windowsHide: false,
    });
    loginChild.once?.('error', () => {});
    return { started: true, reused: false };
  }

  async function stopExportBrowser() {
    if (webSocketUrl && exportChild?.exitCode === null) {
      try { await cdpCommand(webSocketUrl, 'Browser.close', {}, { timeoutMs: 3_000 }); } catch { /* best effort */ }
    }
    exportChild = null;
    webSocketUrl = null;
  }

  async function exportCookies() {
    if (loginChild?.exitCode === null) {
      throw new Error('请先关闭专用 Chrome 登录窗口，再点击“完成授权”');
    }
    loginChild = null;
    fsImpl.mkdirSync(profileDir, { recursive: true });
    const activePortPath = path.join(profileDir, 'DevToolsActivePort');
    fsImpl.rmSync(activePortPath, { force: true });
    exportChild = spawnProcess(resolveChromeExecutable(), buildChromeExportArgs(profileDir), {
      stdio: 'ignore',
      windowsHide: true,
    });
    exportChild.once?.('error', () => {});
    try {
      webSocketUrl = await waitForPort(activePortPath, exportChild, {
        fsImpl,
        timeoutMs: options.startTimeoutMs,
      });
      const result = await cdpCommand(webSocketUrl, 'Storage.getCookies');
      return serializeYouTubeCookies(result?.cookies);
    } finally {
      await stopExportBrowser();
    }
  }

  async function close() {
    await stopExportBrowser();
    if (loginChild?.exitCode === null) {
      try { loginChild.kill(); } catch { /* best effort */ }
    }
    loginChild = null;
  }

  return {
    start,
    exportCookies,
    close,
    isRunning: () => Boolean(
      (loginChild && loginChild.exitCode === null)
      || (exportChild && exportChild.exitCode === null),
    ),
  };
}

module.exports = {
  AUTH_COOKIE_NAMES,
  buildChromeExportArgs,
  buildChromeLoginArgs,
  createYouTubeAuthController,
  findChromeExecutable,
  isYouTubeDomain,
  parseDevToolsActivePort,
  sendCdpCommand,
  serializeYouTubeCookies,
};
